name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to check git history

      - id: check
        name: Check for changes
        run: |
          # Check if there were any commits in the last 24 hours
          if [ -n "$(git rev-list --after="24 hours" ${{ github.sha }})" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Your existing build steps here
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # ... rest of your build steps
